---
title: "Gráficas - Parte 2"
output:
  pdf_document: default
  html_notebook: default
---

Cargue los paquetes en su sesión de R

```{r setup}
library(tidyverse)
library(datos)
```


Agregemos un modelo

```{r}
ggplot(data = diamantes, aes(precio, quilate)) +
  geom_point(aes(color = claridad), alpha = 0.3) +
  geom_smooth(method = "lm") +
  theme_minimal()
```

Creemos un modelo y gráfica por cada valor discreto

```{r}
ggplot(data = diamantes, aes(precio, quilate)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  facet_wrap(~corte) +
  theme_minimal()
```

Grabemos la gráfica en el disco

```{r}
ggsave("cortes.png", height = 8, width = 10)
```


Cargemos la gráfica en una variable

```{r}
p <- ggplot(data = diamantes, aes(precio, quilate)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  facet_wrap(~corte) +
  labs(title = "Precio/quilate por cada corte") +
  theme_minimal()
```

Llamemos la variable

```{r}
p
```

Grabemos la gráfica dentro de la variable

```{r}
ggsave("cortes-nuevo.png", p, height = 8, width = 10)
```

Multiples modelos se pueden comparar mediante agregando más capas

```{r}
diamantes %>%
  ggplot(aes(precio, quilate)) +
  geom_point(aes(color = claridad), alpha = 0.3) +
  geom_smooth(method = "lm", color="pink") +
  geom_smooth(method = "lm", formula=y~poly(x,3), color="red") +
  geom_smooth(method = "lm", formula=y~log(x), color="blue") +
  geom_smooth(color="black")+ # LOESS
  theme_minimal()
```

