---
output:
  xaringan::moon_reader:
    seal: false
    css: "_include/aprender.css"
    nature:
      countIncrementalSlides: yes
      highlightLines: yes
      highlightStyle: github
      ratio: 16:9
resource_files:
  - include
---
---
class: dark, middle, center
# Paquetes en R

---
class: regular

# ¿Que es un paquete en R?


--
* **Expande las habilidades de R**


--
* Programa que **agrega funciones y/o datos** a su sesión de R


--
* Se instala después de instalar R


--
* La fuente más importante se llama CRAN


---
class: regular

# ¿Como se instala un paquete?


--
* Un comando dentro de R baja e instala el paquete


--
* La mayoría de paquetes son bajados de Internet


--
* Para usar un paquete ya instalado, use `library()`


---
class: exercise, middle, center
# Preparar mi computadora

---
class: regular

# Bajar el curso

<br/>

## install.packages("usethis")

## library(usethis)

## use_course("bit.ly/upr-tidyverse")


---
class: regular

# Instale los paquetes necesarios

<br/>

## Navegue al folder llamado "**instalacion**"

## Abra el archivo "**instalar-paquetes.R**"

## Haga click en el botón "**Source**"

---
class: exercise, middle, center
## Ejercicio
# Usar R
### **Archivo:** 01-librerias.Rmd
