---
output:
  xaringan::moon_reader:
    css: "_include/aprender.css"
    seal: false
    nature:
      countIncrementalSlides: yes
      highlightLines: yes
      highlightStyle: github
      ratio: 16:9
resource_files:
  - include
---
---
class: title-slide, middle, center
# Programación de ciclos

---
class:regular
# Multiples archivos 
```{r, eval = FALSE}
lf <- list.files("../ejercicios/datos", "grado")
lf
```
```
## [1] "cuarto_grado.csv" "quinto_grado.csv" "tercer_grado.csv"
```

---
class:regular
# Usando `for`/`in` 

```{r, eval = FALSE}
x <- NULL
for(j in lf) {
  x <- bind_rows(x, read_csv(file.path("../ejercicios/datos", j)))
}
x
```

```
## # A tibble: 144 x 5
##   fecha    nombre             matematica ingles matricula
##   <chr>    <chr>                   <dbl>  <dbl>     <dbl>
## 1 1/1/2015 Hernandez, Rodrigo         90     60       100
## 2 1/2/2015 Hernandez, Rodrigo         85     70       100
## 3 1/3/2015 Hernandez, Rodrigo         70     80       100
## 4 1/4/2015 Hernandez, Rodrigo         75     85       100
## 5 1/5/2015 Hernandez, Rodrigo         70     90       100
```
---
class:regular
# Introduciendo `fs`

```{r, eval = FALSE}
lf <- dir_ls("../ejercicios/datos", regexp = "grado")
lf
```
```
## ../ejercicios/datos/cuarto_grado.csv 
## ../ejercicios/datos/quinto_grado.csv 
## ../ejercicios/datos/tercer_grado.csv 
```
---
class:regular
# Introduciendo `purrr`

```{r, eval = FALSE}
map(lf, read_csv)
```
```
## $`../ejercicios/datos/cuarto_grado.csv`
## $`../ejercicios/datos/quinto_grado.csv`
## $`../ejercicios/datos/tercer_grado.csv`
```
---
class:regular
# Funciones especiales de `purrr`

```{r, eval = FALSE}
map_dfr(lf, read_csv)
```
```
## # A tibble: 144 x 5
##    fecha    nombre             matematica ingles matricula
##    <chr>    <chr>                   <dbl>  <dbl>     <dbl>
##  1 1/1/2015 Hernandez, Rodrigo         90     60       100
##  2 1/2/2015 Hernandez, Rodrigo         85     70       100
##  3 1/3/2015 Hernandez, Rodrigo         70     80       100
##  4 1/4/2015 Hernandez, Rodrigo         75     85       100
##  5 1/5/2015 Hernandez, Rodrigo         70     90       100
##  6 1/6/2015 Hernandez, Rodrigo         66     90       100
```

---
class:regular
# Agrege el nombre del archivo

```{r, eval = FALSE}
map_dfr(lf, read_csv, .id = "archivo")
```

```
## # A tibble: 144 x 6
##    archivo     fecha  nombre  matematica ingles matricula
##    <chr>       <chr>  <chr>        <dbl>  <dbl>     <dbl>
##  1 ejercicios… 1/1/2… Hernan…         90     60       100
##  2 ejercicios… 1/2/2… Hernan…         85     70       100
##  3 ejercicios… 1/3/2… Hernan…         70     80       100
##  4 ejercicios… 1/4/2… Hernan…         75     85       100
##  5 ejercicios… 1/5/2… Hernan…         70     90       100
##  6 ejercicios… 1/6/2… Hernan…         66     90       100
```

